baseurl = "/"
languageCode = "en-us"
title = "Kip Jiang"
theme = "OneSentence"
author = "Kip"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "This Hugo theme was ported from Ivy, a minimalist website generator built in Python. 没有一个春天不会到来！"
    footer = "[Kip Jiang](/) &#183; [Github](https://github.com/KipJiang)"

# comments configure
[params.utteranc]   # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "KipJiang/comments"
    issueTerm = "pathname"

[params.valine]
enable = true
appId = 'AhrO67kSBw2cdWp3AFKzjzI5-MdYXbMMI'
appKey = 'RKBIhU7j518tpSUFbaWh8D2x'
notify = true   # mail notifier , https://github.com/xCss/Valine/wiki
verify = true   # Verification code
avatar = 'mm' 
placeholder = '说点什么吧...（请填写邮件，接收回复提醒）'
visitor = true

highlightjsVersion = "9.12.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "tex"]
highlightjsTheme = "github"
