baseurl = "https://kipjiang.github.io/hugo-theme-OneSentence/"
languageCode = "en-us"
title = "One Sentence"
# theme = "OneSentence"
author = "Kip Jiang"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
enableEmoji = true

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

# [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3
[[menu.main]]
    name = "Notes"
    url = "/note/"
    weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6

[params]
    description = "Hugo theme [**OneSentence**](https://github.com/KipJiang/hugo-theme-OneSentence), using one sentence to describe your article, ported from [hugo-ivy](https://github.com/yihui/hugo-ivy) of [YihuiXie](https://yihui.org/)."
    footer = "[Kip Jiang](/) &#183; [Github](https://github.com/KipJiang) &#183; Theme [OneSentence](https://github.com/KipJiang/hugo-theme-OneSentence)"

# comments configure
[params.utteranc]   # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "KipJiang/hugo-theme-OneSentence"
    issueTerm = "pathname"
    theme = "" # "github-dark"

[params.valine]
    enable = false
    appId = ""
    appKey = ""
    notify = true   # mail notifier , https://github.com/xCss/Valine/wiki
    verify = true   # Verification code
    avatar = 'robohash'
    placeholder = 'Say something... (please fill in the email to receive the reply)'
    visitor = true

highlightjsVersion = "9.12.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "tex"]
highlightjsTheme = "github"
