baseurl = "/"
languageCode = "en-us"
title = "One Sentence"
theme = "OneSentence"
author = "Kip Jiang"

googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4

[params]
    description = "Hugo theme OneSentence, using one sentence to describe your article, ported from hugo-ivy of YihuiXie."
    footer = "[Kip Jiang](/) &#183; [Github](https://github.com/KipJiang)"

# comments configure
[params.utteranc]   # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = 
    repo = 
    issueTerm = "pathname"

[params.valine]
enable = 
appId = 
appKey = 
notify = true   # mail notifier , https://github.com/xCss/Valine/wiki
verify = true   # Verification code
avatar = 'mm' 
placeholder = '说点什么吧...（请填写邮件，接收回复提醒）'
visitor = 

highlightjsVersion = "9.12.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "tex"]
highlightjsTheme = "github"
